FROM python:3.11

COPY . /app

WORKDIR /app

RUN pip3 install -r requirements.txt --no-cache-dir --use-deprecated=legacy-resolver 

RUN apt-get update && \
    apt-get install -y libgl1-mesa-dev

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]